// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_BME280.h>

#define SENSOR_TEMP_ADDRESS 0x76
#define SCREEN_ADDRESS 0x3C ///< See datasheet for Address; 0x3D for 128x64, 0x3C for 128x32

#define SEALEVELPRESSURE_HPA (1011)
#define OLED_RESET     -1 // Reset pin # (or -1 if sharing Arduino reset pin)
#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 64 // OLED display height, in pixels
#define NUMBER_OF_RAWS_DISPLAIED 8

const char DEVICE_LOGIN_NAME[]  = "ac16d9bc-c2b8-48c7-9a7a-4dc5b19d16fb";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;    // Secret device password

//const int LEDPIN =  2;// the number of the LED pin
const long INTERVAL = 1000;           // interval at which to blink (milliseconds)


float humid_1;
float temp_1;
CloudPressure press_1;

float temp;
int humidity;
unsigned long previousMillis = 0;        // will store last time LED was updated
int ledState = LOW;             // ledState used to set the LED

//Temperature sensor
Adafruit_BME280 bme; // I2C

//Display
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humid_1, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(temp_1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(press_1, READ, ON_CHANGE, NULL, 50);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

void displayInit ()
{
  if(!display.begin(SSD1306_SWITCHCAPVCC, SCREEN_ADDRESS)) {
    Serial.println(F("SSD1306 allocation failed"));
    for(;;); // Don't proceed, loop forever
  }
  display.display();
  delay(2000); // Pause for 2 seconds

  // Clear the buffer
  display.clearDisplay();
}

void displayText (String text[])
{
  display.clearDisplay();
  display.setTextSize(1);
  display.setCursor(0,0);
  //display.setTextColor(SSD1306_WHITE, SSD1306_BLACK);
  
  for(int i = 0; i < NUMBER_OF_RAWS_DISPLAIED; i++)
  {
    if (i == 0)
      display.setTextColor(SSD1306_BLACK, SSD1306_WHITE);
    else
      display.setTextColor(SSD1306_WHITE, SSD1306_BLACK);
      
    display.println(text[i]);
  }
  display.display();
}
